- name: Run Clients
  hosts: client

  tasks:
    - name: Create Directory
      ansible.builtin.file:
        path: /home/ansible/mandelbrot
        state: directory

    - name: Copy the key file
      ansible.builtin.copy:
        src: /root/mandelbrot/private_key
        dest: /home/ansible/mandelbrot/private_key

    - name: Change file permissions (chmod 644)
      ansible.builtin.file:
        path: /home/ansible/mandelbrot/private_key
        state: file
        mode: '0600'

    - name: Install git
      ansible.builtin.apt:
        name: git 
        update_cache: yes
      become: yes

    - name: Download official Go tarball
      ansible.builtin.get_url:
        url: "https://go.dev/dl/go1.26.5.linux-amd64.tar.gz"
        dest: "/tmp/go1.22.5.linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract Go to /usr/local
      ansible.builtin.unarchive:
        src: "/tmp/go1.22.5.linux-amd64.tar.gz"
        dest: /usr/local
        remote_src: yes
        creates: /usr/local/go/bin/go
      become: true

    - name: Add Go to global PATH
      ansible.builtin.copy:
        dest: /etc/profile.d/golang.sh
        content: |
          export PATH=$PATH:/usr/local/go/bin
        mode: '0644'
      become: true

    - name: Clone the repo
      ansible.builtin.git:
        repo: git@github.com:navod-abay/distributed-mandelbrot-go.git
        dest: /home/ansible/mandelbrot/repo
        key_file: /home/ansible/mandelbrot/private_key   
        version: master
        accept_hostkey: true

    - name: Create Directory
      ansible.builtin.file:
        path: /home/ansible/mandelbrot/repo/build
        state: directory

    - name: Compile go
      ansible.builtin.command: 
        cmd: /usr/local/go/bin/go build -o /home/ansible/mandelbrot/repo/build/mandelbrotset .
        chdir: /home/ansible/mandelbrot/repo/client
    
    - name: Create systemd unit file for background service
      ansible.builtin.copy:
        dest: /etc/systemd/system/mandelbrot.service
        content: |
          [Unit]
          Description=Mandelbrot Background Worker
          After=network.target

          [Service]
          Type=simple
          User=ansible
          WorkingDirectory=/home/ansible/mandelbrot/repo
          ExecStart=/home/ansible/mandelbrot/repo/build/mandelbrotset -protocolType-RPC
          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'
      become: true

    - name: Start worker service
      ansible.builtin.systemd:
        name: mandelbrot
        state: started
        enabled: true
        daemon_reload: true
      become: true

- name: Run master
  hosts: localhost
  connection: local
  tasks:
    - name: Download official Go tarball
      ansible.builtin.get_url:
        url: "https://go.dev/dl/go1.26.5.linux-amd64.tar.gz"
        dest: "/tmp/go1.22.5.linux-amd64.tar.gz"
        mode: '0644'

    - name: Extract Go to /usr/local
      ansible.builtin.unarchive:
        src: "/tmp/go1.22.5.linux-amd64.tar.gz"
        dest: /usr/local
        remote_src: yes
        creates: /usr/local/go/bin/go
      become: true

    - name: Add Go to global PATH
      ansible.builtin.copy:
        dest: /etc/profile.d/golang.sh
        content: |
          export PATH=$PATH:/usr/local/go/bin
        mode: '0644'
      become: true

    - name: Install unix  time command
      ansible.builtin.apt:
        name: time 
        update_cache: false
      become: yes

    - name: build master
      ansible.builtin.command:
        cmd: /usr/local/go/bin/go build -o /mandelbrot/repo/build/mandelbrotset  .
        chdir: /mandelbrot/repo/master
      environment:
        GOCAHCE: "/tmp/gocache"
        GOPATH: "/tmp/gopath"
    
    - name: run master
      ansible.builtin.command:
        cmd: /mandelbrot/repo/build/mandelbrotset -protocolType=RPC
      async: 3600  # Maximum 1hr
